services:
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis-data:/data
    networks:
      - app-network

  task_scheduler:
    container_name: task_scheduler
    build: ./backend
    ports:
      - 3001:3001
    depends_on:
      - redis
    env_file:
      - ./backend/.env
    networks:
      - app-network

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 3000:80
    depends_on:
      - task_scheduler
    env_file:
      - ./frontend/.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
