services:
  # init:
  #   image: alpine
  #   volumes:
  #     - .:/app
  #   working_dir: /app
  #   entrypoint: sh init-env.sh
  #   command: []

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    # depends_on:
    #   - init
    volumes:
      - ./backend/data/redis-data:/data
    networks:
      - app-network

  backend:
    container_name: backend
    build: ./backend
    ports:
      - 3001:3001
    depends_on:
      - redis
    networks:
      - app-network

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 3000:80
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
